//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin
    {
        public tbl_admin()
        {
            this.tbl_Category = new HashSet<tbl_Category>();
        }
    
        public int ad_id { get; set; }
        public string ad_username { get; set; }
        public string ad_password { get; set; }
    
        public virtual ICollection<tbl_Category> tbl_Category { get; set; }
    }
}
